-- SELECT * FROM Impiegato	WHERE età > 29
-- SELECT * FROM Impiegato WHERE RedditoMensile > 800
-- SELECT * FROM Impiegato WHERE DetrazioneFiscale = 1
-- SELECT * FROM Impiegato WHERE DetrazioneFiscale = 0
-- SELECT * FROM Impiegato WHERE cognome like 'G%' order by cognome asc
-- SELECT sum(RedditoMensile) as Totalereddito FROM Impiegato 